config/routes.rb
Rails.application.routes.draw do
  # index list
  get 'tasks', to: 'tasks#index'
  # create new task
  get 'tasks/new', to: 'tasks#new'
  # task detail page
  get 'tasks/:id', to: 'tasks#show', as: 'task'
  # task create page
  post 'tasks', to: 'tasks#create'
  # show edit form
  get 'tasks/:id/edit', to: 'tasks#edit', as: 'tasks_edit'
  # update task
  patch 'tasks/:id', to: 'tasks#update'
  # delete task
  delete 'tasks/:id', to: 'tasks#destroy'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def new
    @task = Task.new
  end

  def create
    @task = Task.new(task_params)
    @task.save
    redirect_to task_path(@task)
  end

  def show; end

  def edit; end

  def update
    @task.update(task_params)
    redirect_to task_path(@task)
  end

  def destroy
    @task.destroy
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/tasks/_form.html.erb
<%= form_for task do |f|  %>

  <%= f.label :title %>
  <%= f.text_field :title %>

  <%= f.label :details %>
  <%= f.text_field :details %>

  <%= f.label :completed %>
  <%= f.check_box :completed %>

  <%= f.submit %>

<% end %>

app/views/tasks/edit.html.erb
<h1>🗒 Edit @task.title</h1>
<%= render 'form', task: @task %>
<p><%= link_to '🔙 Back to list', tasks_path %></p>

app/views/tasks/index.html.erb
<h1>📝 Tasks</h1>
<% @tasks.each do |task| %>
<h2><%= link_to task.title, task_path(task) %></h2>
<p><%= task.details %></p>
<% if task.completed == true %>
<p>🔳Done</p>
<% else %>
<p>⬜️To-Do</p>
<% end %>
<% end %>
<hr />
<p>🗒 <%= link_to 'Add a new task', tasks_new_path %></p>

app/views/tasks/new.html.erb
<h1>🗒 Create a new task</h1>
<%= render 'form', task: @task %>
<p><%= link_to '🔙 Back to list', tasks_path %></p>

app/views/tasks/show.html.erb
<h1>📝 <%= @task.title %></h1>
<h2><%= @task.details %></h2>
<% if @task.completed == true %>
<p>🔳Done</p>
<% else %>
<p>⬜️To-Do</p>
<% end %>
<p><%= link_to '✏️ Edit this task', tasks_edit_path(@task) %></p>
<p><%= link_to '🗑 Delete this task', task_path, method: :delete %></p>
<p><%= link_to '🔙 Back to list', tasks_path %></p>